In [35]:
# Dependencies
import pandas as pd
import numpy as np

In [36]:
# Creating Dataframe for 2009
csv_path = "State_UI_2009.csv"
unemployment09_df = pd.read_csv(csv_path)
unemployment09_df.head()

,State,Year,Jan.,Feb.,Mar.,April,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.,Avg UI
0,Alabama,2009,7.8,8.4,9.0,9.0,9.8,10.1,10.2,10.4,10.7,10.9,10.5,11.0,9.8
1,Alaska,2009,7.9,8.0,8.5,8.0,8.4,8.4,8.3,8.3,8.4,8.9,8.7,8.8,8.4
2,Arizona,2009,7.0,7.4,7.8,7.7,8.2,8.7,9.2,9.1,9.1,9.3,8.9,9.1,8.5
3,Arkansas,2009,6.4,6.6,6.5,6.5,7.0,7.2,7.4,7.1,7.1,7.6,7.4,7.7,7.0
4,California,2009,10.1,10.5,11.2,11.0,11.5,11.6,11.9,12.2,12.2,12.5,12.3,12.4,11.6

In [57]:
df1 = pd.DataFrame(unemployment09_df)
info_pd09 = pd.DataFrame(unemployment09_df, columns=["State", "Year", "Avg UI"])
info_pd09

             State  Year  Avg UI
0          Alabama  2009     9.8
1           Alaska  2009     8.4
2          Arizona  2009     8.5
3         Arkansas  2009     7.0
4       California  2009    11.6
5         Colorado  2009     7.3
6      Connecticut  2009     8.0
7         Delaware  2009     8.1
8             D.C.  2009    10.8
9          Florida  2009    10.4
10         Georgia  2009     9.8
11          Hawaii  2009     7.0
12           Idaho  2009     8.1
13        Illinois  2009     9.9
14         Indiana  2009     9.9
15            Iowa  2009     6.0
16          Kansas  2009     6.6
17        Kentucky  2009    10.4
18       Louisiana  2009     6.7
19           Maine  2009     8.2
20        Maryland  2009     7.1
21   Massachusetts  2009     8.5
22        Michigan  2009    14.0
23       Minnesota  2009     7.9
24     Mississippi  2009     9.4
25        Missouri  2009     9.0
26         Montana  2009     6.3
27        Nebraska  2009     4.7
28          Nevada  2009    11.8
29   New Hampshire  2009     6.5
30      New Jersey  2009     9.0
31      New Mexico  2009     6.8
32        New York  2009     8.4
33  North Carolina  2009    10.8
34    North Dakota  2009     4.2
35            Ohio  2009    10.3
36        Oklahoma  2009     6.3
37          Oregon  2009    11.5
38    Pennsylvania  2009     8.2
39     Puerto Rico  2009    15.0
40    Rhode Island  2009    12.0
41  South Carolina  2009    11.7
42    South Dakota  2009     4.8
43       Tennessee  2009    10.2
44           Texas  2009     7.5
45            Utah  2009     5.7
46         Vermont  2009     6.9
47        Virginia  2009     6.7
48      Washington  2009     9.1
49   West Virginia  2009     8.0
50       Wisconsin  2009     8.4
51         Wyoming  2009     5.8

In [38]:
# Creating Dataframe for 2010
csv_path = "State_UI_2010.csv"
unemployment10_df = pd.read_csv(csv_path)
unemployment10_df.head()

,State,Year,Jan.,Feb.,March,April,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.,Avg UI
0,Alabama,2010,11.1,11.1,11.0,11.0,10.7,10.3,9.7,9.2,8.9,8.9,9.0,9.1,10.0
1,Alaska,2010,8.5,8.5,8.5,8.4,8.2,7.9,7.7,7.7,7.8,7.9,8.0,8.1,8.1
2,Arizona,2010,9.2,9.5,9.6,9.5,9.6,9.6,9.6,9.7,9.7,9.5,9.4,9.4,9.5
3,Arkansas,2010,7.6,7.7,7.8,7.8,7.7,7.5,7.4,7.5,7.7,7.8,7.9,7.9,7.7
4,California,2010,12.5,12.5,12.6,12.5,12.4,12.3,12.3,12.4,12.4,12.4,12.4,12.5,12.4

In [59]:
df2 = pd.DataFrame(unemployment10_df)
info_pd10 = pd.DataFrame(unemployment10_df, columns=["State", "Year", "Avg UI"])
info_pd10

             State  Year  Avg UI
0          Alabama  2010    10.0
1           Alaska  2010     8.1
2          Arizona  2010     9.5
3         Arkansas  2010     7.7
4       California  2010    12.4
5         Colorado  2010     8.1
6      Connecticut  2010     9.0
7         Delaware  2010     8.7
8               DC  2010    10.5
9          Florida  2010    11.9
10         Georgia  2010    10.2
11          Hawaii  2010     6.6
12           Idaho  2010     9.2
13        Illinois  2010    10.5
14         Indiana  2010     9.9
15            Iowa  2010     6.7
16          Kansas  2010     6.6
17        Kentucky  2010    10.3
18       Louisiana  2010     7.4
19           Maine  2010     7.9
20        Maryland  2010     7.4
21   Massachusetts  2010     8.9
22        Michigan  2010    13.3
23       Minnesota  2010     7.1
24     Mississippi  2010    10.7
25        Missouri  2010     9.4
26         Montana  2010     7.2
27        Nebraska  2010     4.7
28          Nevada  2010    14.0
29   New Hampshire  2010     6.1
30      New Jersey  2010     9.6
31      New Mexico  2010     8.5
32        New York  2010     8.4
33  North Carolina  2010    10.2
34    North Dakota  2010     3.8
35            Ohio  2010    10.4
36        Oklahoma  2010     6.8
37          Oregon  2010    10.6
38    Pennsylvania  2010     9.0
39     Puerto Rico  2010    16.1
40    Rhode Island  2010    12.0
41  South Carolina  2010    11.3
42    South Dakota  2010     4.6
43       Tennessee  2010    10.0
44           Texas  2010     8.2
45            Utah  2010     7.3
46         Vermont  2010     6.1
47        Virginia  2010     7.0
48      Washington  2010     9.2
49   West Virginia  2010     9.1
50       Wisconsin  2010     8.1
51         Wyoming  2010     6.9

In [40]:
# Creating Dataframe for 2011
csv_path = "State_UI_2011.csv"
unemployment11_df = pd.read_csv(csv_path)
unemployment11_df.head()

,State,Year,Jan,Feb,Mar,Apr,May,June,July,Aug,Sept,Oct,Nov,Dec,Avg UI
0,Alabama,2011,9.3,9.3,9.2,9.3,9.6,9.9,10.0,9.9,9.8,9.3,8.7,8.1,9.4
1,Alaska,2011,7.7,7.6,7.4,7.3,7.4,7.5,7.7,7.7,7.6,7.4,7.3,7.3,7.5
2,Arizona,2011,9.6,9.6,9.5,9.3,9.1,9.3,9.4,9.3,9.1,9.0,8.7,8.7,9.2
3,Arkansas,2011,7.8,7.8,7.8,7.7,7.8,8.1,8.2,8.3,8.3,8.2,8.0,7.7,8.0
4,California,2011,12.4,12.2,12.0,11.9,11.7,11.8,12.0,12.1,11.9,11.7,11.3,11.1,11.8

In [60]:
df3 = pd.DataFrame(unemployment11_df)
info_pd11 = pd.DataFrame(unemployment11_df, columns=["State", "Year", "Avg UI"])
info_pd11

             State  Year  Avg UI
0          Alabama  2011     9.4
1           Alaska  2011     7.5
2          Arizona  2011     9.2
3         Arkansas  2011     8.0
4       California  2011    11.8
5         Colorado  2011     8.6
6      Connecticut  2011     8.9
7         Delaware  2011     8.1
8             D.C.  2011    10.3
9          Florida  2011    10.7
10         Georgia  2011    10.1
11          Hawaii  2011     6.3
12           Idaho  2011     9.2
13        Illinois  2011     9.4
14         Indiana  2011     8.7
15            Iowa  2011     6.0
16          Kansas  2011     6.6
17        Kentucky  2011     9.8
18       Louisiana  2011     7.5
19           Maine  2011     7.5
20        Maryland  2011     7.0
21   Massachusetts  2011     7.6
22        Michigan  2011    10.4
23       Minnesota  2011     6.6
24     Mississippi  2011    10.4
25        Missouri  2011     8.8
26         Montana  2011     7.4
27        Nebraska  2011     4.2
28          Nevada  2011    13.1
29   New Hampshire  2011     5.2
30      New Jersey  2011     9.3
31      New Mexico  2011     7.2
32        New York  2011     8.0
33  North Carolina  2011    10.0
34    North Dakota  2011     3.4
35            Ohio  2011     8.9
36        Oklahoma  2011     5.9
37          Oregon  2011     9.6
38    Pennsylvania  2011     7.9
39     Puerto Rico  2011    15.8
40    Rhode Island  2011    10.8
41  South Carolina  2011    10.3
42    South Dakota  2011     4.7
43       Tennessee  2011     9.5
44           Texas  2011     8.2
45            Utah  2011     7.2
46         Vermont  2011     5.5
47        Virginia  2011     6.3
48      Washington  2011     9.1
49   West Virginia  2011     8.5
50       Wisconsin  2011     7.5
51         Wyoming  2011     5.9

In [42]:
# Creating Dataframe for 2012
csv_path = "State_UI_2012.csv"
unemployment12_df = pd.read_csv(csv_path)
unemployment12_df.head()

,State,Year,Jan,Feb,Mar,Apr,May,June,July,Aug,Sept,Oct,Nov,Dec,Avg UI
0,Alabama,2012,7.8,7.6,7.3,7.2,7.4,7.8,8.3,8.5,8.3,8.1,7.5,7.1,7.7
1,Alaska,2012,7.2,7.1,7.0,6.9,7.0,7.3,7.7,7.8,7.5,7.1,6.8,6.6,7.2
2,Arizona,2012,8.7,8.7,8.6,8.2,8.2,8.2,8.3,8.3,8.2,8.1,7.8,7.9,8.3
3,Arkansas,2012,7.6,7.6,7.4,7.2,7.3,7.2,7.3,7.3,7.1,7.2,7.0,7.1,7.3
4,California,2012,10.9,10.9,11.0,10.9,10.8,10.7,10.7,10.6,10.2,10.1,9.8,9.8,10.5

In [61]:
df4 = pd.DataFrame(unemployment12_df)
info_pd12 = pd.DataFrame(unemployment12_df, columns=["State", "Year", "Avg UI"])
info_pd12

             State  Year  Avg UI
0          Alabama  2012     7.7
1           Alaska  2012     7.2
2          Arizona  2012     8.3
3         Arkansas  2012     7.3
4       California  2012    10.5
5         Colorado  2012     7.9
6      Connecticut  2012     8.3
7         Delaware  2012     6.8
8             D.C.  2012     9.1
9          Florida  2012     8.7
10         Georgia  2012     9.0
11          Hawaii  2012     6.0
12           Idaho  2012     7.5
13        Illinois  2012     8.9
14         Indiana  2012     8.2
15            Iowa  2012     5.2
16          Kansas  2012     6.0
17        Kentucky  2012     8.4
18       Louisiana  2012     6.9
19           Maine  2012     7.3
20        Maryland  2012     6.7
21   Massachusetts  2012     6.5
22        Michigan  2012     8.9
23       Minnesota  2012     5.7
24     Mississippi  2012     9.0
25        Missouri  2012     7.1
26         Montana  2012     6.2
27        Nebraska  2012     3.9
28          Nevada  2012    11.7
29   New Hampshire  2012     5.4
30      New Jersey  2012     9.4
31      New Mexico  2012     6.7
32        New York  2012     8.6
33  North Carolina  2012     9.5
34    North Dakota  2012     3.1
35            Ohio  2012     7.2
36        Oklahoma  2012     5.2
37          Oregon  2012     8.6
38    Pennsylvania  2012     7.8
39     Puerto Rico  2012    14.2
40    Rhode Island  2012    10.8
41  South Carolina  2012     9.0
42    South Dakota  2012     4.4
43       Tennessee  2012     8.0
44           Texas  2012     6.9
45            Utah  2012     5.7
46         Vermont  2012     5.0
47        Virginia  2012     5.7
48      Washington  2012     8.2
49   West Virginia  2012     7.2
50       Wisconsin  2012     7.0
51         Wyoming  2012     5.3

In [44]:
# Creating Dataframe for 2013
csv_path = "State_UI_2013.csv"
unemployment13_df = pd.read_csv(csv_path)
unemployment13_df.head()

,State,Year,Jan,Feb,Mar,Apr,May,June,July,Aug,Sept,Oct,Nov,Dec,Avg UI
0,Alabama,2013,6.9,7.2,7.2,6.9,6.8,6.5,6.3,6.3,6.4,6.5,6.2,6.1,6.6
1,Alaska,2013,6.7,6.5,6.2,6.0,5.9,6.1,6.3,6.5,6.5,6.5,6.4,6.4,6.3
2,Arizona,2013,8.0,7.9,7.9,7.9,7.8,8.0,8.0,8.3,8.3,8.2,7.8,7.6,8.0
3,Arkansas,2013,7.2,7.2,7.2,7.1,7.3,7.3,7.4,7.4,7.4,7.5,7.5,7.4,7.3
4,California,2013,9.8,9.6,9.4,9.0,8.6,8.5,8.7,8.9,8.7,8.7,8.5,8.3,8.9

In [62]:
df5 = pd.DataFrame(unemployment13_df)
info_pd13 = pd.DataFrame(unemployment13_df, columns=["State", "Year", "Avg UI"])
info_pd13

             State  Year  Avg UI
0          Alabama  2013     6.6
1           Alaska  2013     6.3
2          Arizona  2013     8.0
3         Arkansas  2013     7.3
4       California  2013     8.9
5         Colorado  2013     6.9
6      Connecticut  2013     7.9
7         Delaware  2013     7.1
8             D.C.  2013     8.6
9          Florida  2013     7.1
10         Georgia  2013     8.3
11          Hawaii  2013     4.7
12           Idaho  2013     6.3
13        Illinois  2013     9.1
14         Indiana  2013     8.1
15            Iowa  2013     4.7
16          Kansas  2013     5.6
17        Kentucky  2013     8.2
18       Louisiana  2013     6.5
19           Maine  2013     6.9
20        Maryland  2013     6.7
21   Massachusetts  2013     6.9
22        Michigan  2013     8.7
23       Minnesota  2013     5.1
24     Mississippi  2013     8.8
25        Missouri  2013     6.7
26         Montana  2013     5.4
27        Nebraska  2013     3.9
28          Nevada  2013     9.4
29   New Hampshire  2013     5.3
30      New Jersey  2013     8.6
31      New Mexico  2013     6.7
32        New York  2013     7.7
33  North Carolina  2013     8.6
34    North Dakota  2013     3.0
35            Ohio  2013     7.2
36        Oklahoma  2013     5.2
37          Oregon  2013     7.9
38    Pennsylvania  2013     7.6
39     Puerto Rico  2013    14.2
40    Rhode Island  2013     9.1
41  South Carolina  2013     7.9
42    South Dakota  2013     4.0
43       Tennessee  2013     8.2
44           Texas  2013     6.3
45            Utah  2013     4.7
46         Vermont  2013     4.4
47        Virginia  2013     5.5
48      Washington  2013     7.0
49   West Virginia  2013     6.5
50       Wisconsin  2013     6.8
51         Wyoming  2013     4.7

In [46]:
# Creating Dataframe for 2014
csv_path = "State_UI_2014.csv"
unemployment14_df = pd.read_csv(csv_path)
unemployment14_df.head()

,State,Year,Jan,Feb,Mar,Apr,May,June,July,Aug,Sept,Oct,Nov,Dec,Avg UI
0,Alabama,2014,6.1,6.4,6.7,6.9,6.8,6.8,7.0,6.9,6.6,6.3,6.0,5.7,6.5
1,Alaska,2014,6.4,6.5,6.6,6.4,6.4,6.4,6.5,6.8,6.8,6.8,6.6,6.3,6.5
2,Arizona,2014,7.5,7.3,7.3,6.9,6.8,6.9,7.0,7.1,6.9,6.8,6.8,6.7,7.0
3,Arkansas,2014,7.3,7.1,6.9,6.6,6.4,6.2,6.2,6.3,6.2,6.0,5.8,5.7,6.4
4,California,2014,8.1,8.0,8.1,7.8,7.6,7.4,7.4,7.4,7.3,7.3,7.2,7.0,7.6

In [63]:
df6 = pd.DataFrame(unemployment14_df)
info_pd14 = pd.DataFrame(unemployment14_df, columns=["State", "Year", "Avg UI"])
info_pd14

             State  Year  Avg UI
0          Alabama  2014     6.5
1           Alaska  2014     6.5
2          Arizona  2014     7.0
3         Arkansas  2014     6.4
4       California  2014     7.6
5         Colorado  2014     5.3
6      Connecticut  2014     6.7
7         Delaware  2014     6.1
8             D.C.  2014     7.5
9          Florida  2014     6.1
10         Georgia  2014     7.4
11          Hawaii  2014     4.3
12           Idaho  2014     4.7
13        Illinois  2014     7.3
14         Indiana  2014     5.9
15            Iowa  2014     4.4
16          Kansas  2014     4.7
17        Kentucky  2014     7.1
18       Louisiana  2014     5.4
19           Maine  2014     5.8
20        Maryland  2014     5.8
21   Massachusetts  2014     6.0
22        Michigan  2014     7.3
23       Minnesota  2014     4.4
24     Mississippi  2014     7.6
25        Missouri  2014     6.2
26         Montana  2014     4.7
27        Nebraska  2014     3.5
28          Nevada  2014     7.7
29   New Hampshire  2014     4.5
30      New Jersey  2014     6.7
31      New Mexico  2014     6.6
32        New York  2014     6.5
33  North Carolina  2014     6.3
34    North Dakota  2014     2.7
35            Ohio  2014     5.7
36        Oklahoma  2014     4.7
37          Oregon  2014     6.9
38    Pennsylvania  2014     5.7
39     Puerto Rico  2014    14.0
40    Rhode Island  2014     8.0
41  South Carolina  2014     6.0
42    South Dakota  2014     3.6
43       Tennessee  2014     6.9
44           Texas  2014     5.2
45            Utah  2014     3.7
46         Vermont  2014     3.9
47        Virginia  2014     5.1
48      Washington  2014     6.0
49   West Virginia  2014     6.2
50       Wisconsin  2014     5.7
51         Wyoming  2014     4.3

In [48]:
# Creating Dataframe for 2015
csv_path = "State_UI_2015.csv"
unemployment15_df = pd.read_csv(csv_path)
unemployment15_df.head()

,State,Year,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.,Avg UI
0,Alabama,2015,6.0,5.8,5.7,5.8,6.1,6.1,6.2,6.2,6.0,5.9,6.0,6.2,6.0
1,Alaska,2015,6.3,6.3,6.5,6.7,6.8,6.8,6.7,6.6,6.4,6.4,6.4,6.5,6.5
2,Arizona,2015,6.6,6.5,6.2,6.0,5.8,5.9,6.1,6.3,6.3,6.1,6.0,5.8,6.1
3,Arkansas,2015,5.6,5.5,5.6,5.7,5.7,5.7,5.6,5.4,5.2,5.1,5.0,4.8,5.4
4,California,2015,6.9,6.7,6.5,6.3,6.4,6.3,6.2,6.1,5.9,5.8,5.7,5.8,6.2

In [64]:
df7 = pd.DataFrame(unemployment15_df)
info_pd15 = pd.DataFrame(unemployment15_df, columns=["State", "Year", "Avg UI"])
info_pd15

             State  Year  Avg UI
0          Alabama  2015     6.0
1           Alaska  2015     6.5
2          Arizona  2015     6.1
3         Arkansas  2015     5.4
4       California  2015     6.2
5         Colorado  2015     4.1
6      Connecticut  2015     5.7
7         Delaware  2015     4.8
8             D.C.  2015     7.1
9          Florida  2015     5.4
10         Georgia  2015     6.0
11          Hawaii  2015     3.7
12           Idaho  2015     4.0
13        Illinois  2015     5.8
14         Indiana  2015     5.0
15            Iowa  2015     3.8
16          Kansas  2015     4.3
17        Kentucky  2015     5.1
18       Louisiana  2015     6.4
19           Maine  2015     4.6
20        Maryland  2015     5.3
21   Massachusetts  2015     4.7
22        Michigan  2015     5.4
23       Minnesota  2015     3.8
24     Mississippi  2015     6.5
25        Missouri  2015     5.4
26         Montana  2015     4.1
27        Nebraska  2015     2.8
28          Nevada  2015     6.8
29   New Hampshire  2015     3.6
30      New Jersey  2015     5.9
31      New Mexico  2015     6.4
32        New York  2015     5.4
33  North Carolina  2015     5.6
34    North Dakota  2015     2.9
35            Ohio  2015     4.9
36        Oklahoma  2015     4.2
37          Oregon  2015     5.7
38    Pennsylvania  2015     5.2
39     Puerto Rico  2015    12.1
40    Rhode Island  2015     5.8
41  South Carolina  2015     6.2
42    South Dakota  2015     3.5
43       Tennessee  2015     5.9
44           Texas  2015     4.3
45            Utah  2015     3.5
46         Vermont  2015     3.7
47        Virginia  2015     4.6
48      Washington  2015     5.6
49   West Virginia  2015     6.9
50       Wisconsin  2015     4.5
51         Wyoming  2015     4.1

In [50]:
# Creating Dataframe for 2016
csv_path = "State_UI_2016.csv"
unemployment16_df = pd.read_csv(csv_path)
unemployment16_df.head()

,State,Year,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.,Avg UI
0,Alabama,2016,6.0,6.0,5.9,5.9,5.8,5.8,5.8,5.8,5.9,5.9,5.8,5.7,5.9
1,Alaska,2016,6.7,6.8,6.8,6.8,6.9,6.9,7.0,7.0,7.0,7.0,7.0,7.0,6.9
2,Arizona,2016,5.7,5.6,5.5,5.5,5.4,5.4,5.3,5.3,5.2,5.2,5.2,5.2,5.4
3,Arkansas,2016,4.2,4.1,4.1,4.0,4.0,4.0,3.9,3.9,3.9,3.8,3.8,3.7,4.0
4,California,2016,5.7,5.6,5.6,5.5,5.5,5.5,5.5,5.4,5.4,5.4,5.4,5.3,5.5

In [65]:
df8 = pd.DataFrame(unemployment16_df)
info_pd16 = pd.DataFrame(unemployment16_df, columns=["State", "Year", "Avg UI"])
info_pd16

             State  Year  Avg UI
0          Alabama  2016     5.9
1           Alaska  2016     6.9
2          Arizona  2016     5.4
3         Arkansas  2016     4.0
4       California  2016     5.5
5         Colorado  2016     3.3
6      Connecticut  2016     5.2
7         Delaware  2016     4.5
8             D.C.  2016     6.1
9          Florida  2016     4.8
10         Georgia  2016     5.4
11          Hawaii  2016     3.0
12           Idaho  2016     3.8
13        Illinois  2016     5.8
14         Indiana  2016     4.4
15            Iowa  2016     3.6
16          Kansas  2016     4.0
17        Kentucky  2016     5.2
18       Louisiana  2016     6.1
19           Maine  2016     3.8
20        Maryland  2016     4.4
21   Massachusetts  2016     3.9
22        Michigan  2016     5.0
23       Minnesota  2016     3.9
24     Mississippi  2016     5.8
25        Missouri  2016     4.6
26         Montana  2016     4.1
27        Nebraska  2016     3.1
28          Nevada  2016     5.7
29   New Hampshire  2016     2.9
30      New Jersey  2016     5.0
31      New Mexico  2016     6.7
32        New York  2016     4.9
33  North Carolina  2016     5.1
34    North Dakota  2016     3.1
35            Ohio  2016     5.1
36        Oklahoma  2016     4.8
37          Oregon  2016     4.8
38    Pennsylvania  2016     5.4
39    Rhode Island  2016     5.2
40  South Carolina  2016     5.0
41    South Dakota  2016     3.0
42       Tennessee  2016     4.7
43           Texas  2016     4.6
44            Utah  2016     3.4
45         Vermont  2016     3.2
46        Virginia  2016     4.1
47      Washington  2016     5.3
48   West Virginia  2016     6.1
49       Wisconsin  2016     4.0
50         Wyoming  2016     5.3
51     Puerto Rico  2016    11.8

In [52]:
# Creating Dataframe for 2017
csv_path = "State_UI_2017.csv"
unemployment17_df = pd.read_csv(csv_path)
unemployment17_df.head()

,State,Year,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sept.,Oct.,Nov.,Dec.,Avg UI
0,Alabama,2017,5.5,5.3,5.0,4.8,4.6,4.3,4.1,4.0,3.9,3.8,3.8,3.8,4.4
1,Alaska,2017,7.0,7.0,7.1,7.1,7.1,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.1
2,Arizona,2017,5.2,5.1,5.1,5.0,4.9,4.8,4.7,4.7,4.7,4.7,4.7,4.7,4.9
3,Arkansas,2017,3.7,3.6,3.6,3.6,3.6,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7
4,California,2017,5.2,5.1,5.0,5.0,4.9,4.8,4.7,4.6,4.5,4.5,4.5,4.5,4.8

In [66]:
df9 = pd.DataFrame(unemployment17_df)
info_pd17 = pd.DataFrame(unemployment17_df, columns=["State", "Year", "Avg UI"])
info_pd17

             State  Year  Avg UI
0          Alabama  2017     4.4
1           Alaska  2017     7.1
2          Arizona  2017     4.9
3         Arkansas  2017     3.7
4       California  2017     4.8
5         Colorado  2017     2.8
6      Connecticut  2017     4.7
7         Delaware  2017     4.6
8             D.C.  2017     6.1
9          Florida  2017     4.2
10         Georgia  2017     4.8
11          Hawaii  2017     2.4
12           Idaho  2017     3.2
13        Illinois  2017     5.0
14         Indiana  2017     3.6
15            Iowa  2017     3.1
16          Kansas  2017     3.6
17        Kentucky  2017     4.9
18       Louisiana  2017     5.2
19           Maine  2017     3.3
20        Maryland  2017     4.1
21   Massachusetts  2017     3.7
22        Michigan  2017     4.6
23       Minnesota  2017     3.5
24     Mississippi  2017     5.1
25        Missouri  2017     3.7
26         Montana  2017     4.0
27        Nebraska  2017     2.9
28          Nevada  2017     5.0
29   New Hampshire  2017     2.7
30      New Jersey  2017     4.6
31      New Mexico  2017     6.2
32        New York  2017     4.7
33  North Carolina  2017     4.6
34    North Dakota  2017     2.6
35            Ohio  2017     5.0
36        Oklahoma  2017     4.3
37          Oregon  2017     4.1
38    Pennsylvania  2017     4.9
39    Rhode Island  2017     4.5
40  South Carolina  2017     4.3
41    South Dakota  2017     3.3
42       Tennessee  2017     3.7
43           Texas  2017     4.3
44            Utah  2017     3.3
45         Vermont  2017     3.0
46        Virginia  2017     3.8
47      Washington  2017     4.8
48   West Virginia  2017     5.2
49       Wisconsin  2017     3.3
50         Wyoming  2017     4.2
51     Puerto Rico  2017    10.9

In [85]:
# Merge two dataframes using an inner join
merge_table1 = pd.merge(info_pd09, info_pd10, on="State")

In [86]:
# adding 2011 data to merge
merge_table2 = pd.merge(merge_table1, info_pd11, on="State")

In [87]:
# adding 2012 data to merge
merge_table3 = pd.merge(merge_table2, info_pd12, on="State")

In [88]:
# adding 2013 data to merge
merge_table4 = pd.merge(merge_table3, info_pd13, on="State")

In [89]:
# adding 2014 data to merge
merge_table5 = pd.merge(merge_table4, info_pd14, on="State")

In [90]:
# adding 2015 data to merge
merge_table6 = pd.merge(merge_table5, info_pd15, on="State")

In [91]:
# adding 2016 data to merge
merge_table7 = pd.merge(merge_table6, info_pd16, on="State")

In [93]:
# adding 2017 data to merge
merge_table8 = pd.merge(merge_table7, info_pd17, on="State")
merge_table8

,State,Year_x,Avg UI_x,Year_y,Avg UI_y,Year_x,Avg UI_x,Year_y,Avg UI_y,Year_x,Avg UI_x,Year_y,Avg UI_y,Year_x,Avg UI_x,Year_y,Avg UI_y,Year,Avg UI
0,Alabama,2009,9.8,2010,10.0,2011,9.4,2012,7.7,2013,6.6,2014,6.5,2015,6.0,2016,5.9,2017,4.4
1,Alaska,2009,8.4,2010,8.1,2011,7.5,2012,7.2,2013,6.3,2014,6.5,2015,6.5,2016,6.9,2017,7.1
2,Arizona,2009,8.5,2010,9.5,2011,9.2,2012,8.3,2013,8.0,2014,7.0,2015,6.1,2016,5.4,2017,4.9
3,Arkansas,2009,7.0,2010,7.7,2011,8.0,2012,7.3,2013,7.3,2014,6.4,2015,5.4,2016,4.0,2017,3.7
4,California,2009,11.6,2010,12.4,2011,11.8,2012,10.5,2013,8.9,2014,7.6,2015,6.2,2016,5.5,2017,4.8
5,Colorado,2009,7.3,2010,8.1,2011,8.6,2012,7.9,2013,6.9,2014,5.3,2015,4.1,2016,3.3,2017,2.8
6,Connecticut,2009,8.0,2010,9.0,2011,8.9,2012,8.3,2013,7.9,2014,6.7,2015,5.7,2016,5.2,2017,4.7
7,Delaware,2009,8.1,2010,8.7,2011,8.1,2012,6.8,2013,7.1,2014,6.1,2015,4.8,2016,4.5,2017,4.6
8,Florida,2009,10.4,2010,11.9,2011,10.7,2012,8.7,2013,7.1,2014,6.1,2015,5.4,2016,4.8,2017,4.2
9,Georgia,2009,9.8,2010,10.2,2011,10.1,2012,9.0,2013,8.3,2014,7.4,2015,6.0,2016,5.4,2017,4.8
10,Hawaii,2009,7.0,2010,6.6,2011,6.3,2012,6.0,2013,4.7,2014,4.3,2015,3.7,2016,3.0,2017,2.4
11,Idaho,2009,8.1,2010,9.2,2011,9.2,2012,7.5,2013,6.3,2014,4.7,2015,4.0,2016,3.8,2017,3.2
12,Illinois,2009,9.9,2010,10.5,2011,9.4,2012,8.9,2013,9.1,2014,7.3,2015,5.8,2016,5.8,2017,5.0
13,Indiana,2009,9.9,2010,9.9,2011,8.7,2012,8.2,2013,8.1,2014,5.9,2015,5.0,2016,4.4,2017,3.6
14,Iowa,2009,6.0,2010,6.7,2011,6.0,2012,5.2,2013,4.7,2014,4.4,2015,3.8,2016,3.6,2017,3.1
15,Kansas,2009,6.6,2010,6.6,2011,6.6,2012,6.0,2013,5.6,2014,4.7,2015,4.3,2016,4.0,2017,3.6
16,Kentucky,2009,10.4,2010,10.3,2011,9.8,2012,8.4,2013,8.2,2014,7.1,2015,5.1,2016,5.2,2017,4.9
17,Louisiana,2009,6.7,2010,7.4,2011,7.5,2012,6.9,2013,6.5,2014,5.4,2015,6.4,2016,6.1,2017,5.2
18,Maine,2009,8.2,2010,7.9,2011,7.5,2012,7.3,2013,6.9,2014,5.8,2015,4.6,2016,3.8,2017,3.3
19,Maryland,2009,7.1,2010,7.4,2011,7.0,2012,6.7,2013,6.7,2014,5.8,2015,5.3,2016,4.4,2017,4.1
20,Massachusetts,2009,8.5,2010,8.9,2011,7.6,2012,6.5,2013,6.9,2014,6.0,2015,4.7,2016,3.9,2017,3.7
21,Michigan,2009,14.0,2010,13.3,2011,10.4,2012,8.9,2013,8.7,2014,7.3,2015,5.4,2016,5.0,2017,4.6
22,Minnesota,2009,7.9,2010,7.1,2011,6.6,2012,5.7,2013,5.1,2014,4.4,2015,3.8,2016,3.9,2017,3.5
23,Mississippi,2009,9.4,2010,10.7,2011,10.4,2012,9.0,2013,8.8,2014,7.6,2015,6.5,2016,5.8,2017,5.1
24,Missouri,2009,9.0,2010,9.4,2011,8.8,2012,7.1,2013,6.7,2014,6.2,2015,5.4,2016,4.6,2017,3.7
25,Montana,2009,6.3,2010,7.2,2011,7.4,2012,6.2,2013,5.4,2014,4.7,2015,4.1,2016,4.1,2017,4.0
26,Nebraska,2009,4.7,2010,4.7,2011,4.2,2012,3.9,2013,3.9,2014,3.5,2015,2.8,2016,3.1,2017,2.9
27,Nevada,2009,11.8,2010,14.0,2011,13.1,2012,11.7,2013,9.4,2014,7.7,2015,6.8,2016,5.7,2017,5.0
28,New Hampshire,2009,6.5,2010,6.1,2011,5.2,2012,5.4,2013,5.3,2014,4.5,2015,3.6,2016,2.9,2017,2.7
29,New Jersey,2009,9.0,2010,9.6,2011,9.3,2012,9.4,2013,8.6,2014,6.7,2015,5.9,2016,5.0,2017,4.6
30,New Mexico,2009,6.8,2010,8.5,2011,7.2,2012,6.7,2013,6.7,2014,6.6,2015,6.4,2016,6.7,2017,6.2
31,New York,2009,8.4,2010,8.4,2011,8.0,2012,8.6,2013,7.7,2014,6.5,2015,5.4,2016,4.9,2017,4.7
32,North Carolina,2009,10.8,2010,10.2,2011,10.0,2012,9.5,2013,8.6,2014,6.3,2015,5.6,2016,5.1,2017,4.6
33,North Dakota,2009,4.2,2010,3.8,2011,3.4,2012,3.1,2013,3.0,2014,2.7,2015,2.9,2016,3.1,2017,2.6
34,Ohio,2009,10.3,2010,10.4,2011,8.9,2012,7.2,2013,7.2,2014,5.7,2015,4.9,2016,5.1,2017,5.0
35,Oklahoma,2009,6.3,2010,6.8,2011,5.9,2012,5.2,2013,5.2,2014,4.7,2015,4.2,2016,4.8,2017,4.3
36,Oregon,2009,11.5,2010,10.6,2011,9.6,2012,8.6,2013,7.9,2014,6.9,2015,5.7,2016,4.8,2017,4.1
37,Pennsylvania,2009,8.2,2010,9.0,2011,7.9,2012,7.8,2013,7.6,2014,5.7,2015,5.2,2016,5.4,2017,4.9
38,Puerto Rico,2009,15.0,2010,16.1,2011,15.8,2012,14.2,2013,14.2,2014,14.0,2015,12.1,2016,11.8,2017,10.9
39,Rhode Island,2009,12.0,2010,12.0,2011,10.8,2012,10.8,2013,9.1,2014,8.0,2015,5.8,2016,5.2,2017,4.5
40,South Carolina,2009,11.7,2010,11.3,2011,10.3,2012,9.0,2013,7.9,2014,6.0,2015,6.2,2016,5.0,2017,4.3
41,South Dakota,2009,4.8,2010,4.6,2011,4.7,2012,4.4,2013,4.0,2014,3.6,2015,3.5,2016,3.0,2017,3.3
42,Tennessee,2009,10.2,2010,10.0,2011,9.5,2012,8.0,2013,8.2,2014,6.9,2015,5.9,2016,4.7,2017,3.7
43,Texas,2009,7.5,2010,8.2,2011,8.2,2012,6.9,2013,6.3,2014,5.2,2015,4.3,2016,4.6,2017,4.3
44,Utah,2009,5.7,2010,7.3,2011,7.2,2012,5.7,2013,4.7,2014,3.7,2015,3.5,2016,3.4,2017,3.3
45,Vermont,2009,6.9,2010,6.1,2011,5.5,2012,5.0,2013,4.4,2014,3.9,2015,3.7,2016,3.2,2017,3.0
46,Virginia,2009,6.7,2010,7.0,2011,6.3,2012,5.7,2013,5.5,2014,5.1,2015,4.6,2016,4.1,2017,3.8
47,Washington,2009,9.1,2010,9.2,2011,9.1,2012,8.2,2013,7.0,2014,6.0,2015,5.6,2016,5.3,2017,4.8
48,West Virginia,2009,8.0,2010,9.1,2011,8.5,2012,7.2,2013,6.5,2014,6.2,2015,6.9,2016,6.1,2017,5.2
49,Wisconsin,2009,8.4,2010,8.1,2011,7.5,2012,7.0,2013,6.8,2014,5.7,2015,4.5,2016,4.0,2017,3.3
50,Wyoming,2009,5.8,2010,6.9,2011,5.9,2012,5.3,2013,4.7,2014,4.3,2015,4.1,2016,5.3,2017,4.2